### ISSUE TITLE
NameError: name 'plot_prediction' is not defined

### ISSUE THREAD

**Issue by C24IO** [kenstler/aws-ml-iot-lab#3]
https://github.com/kenstler/aws-ml-iot-lab/blob/58e1ee5849ea6502601f4b70f94e5b218a520c21/Prep_Challenge/SSD_Face_Detection_SageMaker_Endpoint.ipynb#L499

`NameErrorTraceback (most recent call last)
<ipython-input-12-c8fd16e476e1> in <module>()
----> 1 plot_prediction(response, test_img_array)

NameError: name 'plot_prediction' is not defined
`

**Comment by kenstler** [comment]
Added missing function to notebook.
